name: ztour_mobile
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  
  flutter_translate: ^1.6.0
  intl_translation: ^0.17.1
  flutter_swiper: ^1.1.6
  flutter_custom_clippers: ^1.1.1
  intro_views_flutter: ^2.8.1
  wave: 0.1.0
  flutter_form_builder: ^3.13.6
  url_launcher: ^5.5.0
  bottomreveal: ^1.0.0
  charts_flutter: ^0.9.0
  animated_floatactionbuttons: ^0.1.0
  intl: ^0.16.1
  flare_flutter: 2.0.6
  cached_network_image: 
  flutter_staggered_grid_view: ^0.3.0
  flutter_auth_buttons:
  css_colors:
  crop: 0.4.1
  share: ^0.6.4+3
  animator: ^2.0.1  
  bmnav: ^0.3.4
  dynamic_theme:
  
  


  cloud_firestore: 
  firebase_core: 
  firebase_analytics: 
  firebase_dynamic_links: 
  flutter_signin_button: 
  firebase_auth_ui:

 
  
  flutter_polyline_points: 0.2.3
  json_annotation: ^3.0.0
  fluro: ^1.1.0
  flutter_webview_plugin: 
  timeago: ^2.0.27
  http: ^0.12.0+2
  rxdart: ^0.22.3
  video_player:
  get_it: 5.0.1
  provider: ^4.1.3
  stacked: ^1.6.0
  stacked_services: 0.5.4+3
  spreadsheet_decoder: ^1.2.0
 
  stripe_payment: ^1.0.7
  flutter_credit_card: ^0.1.3
  splashscreen: ^1.2.0
  progress_dialog: ^1.2.4
  flushbar: ^1.10.4
  credit_card_input_form: ^2.0.3
  credit_card_number_validator: ^1.0.4
  instant: ^0.3.2
  webview_flutter: ^0.3.19+9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: 1.0.0
  carousel_pro: ^1.0.0
  csv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.4.4
  firebase_database: 3.1.6
  font_awesome_flutter: 8.7.0
  list_wheel_scroll_view_x: ^0.0.1
  flutter_launcher_icons: any 
  google_maps_flutter:
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  
flutter_icons:
  android: "launcher_icon"
  image_path: 'assets/LogoZtour/icon1.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/google_logo.png
    - assets/Animal_Information.xlsx
    - assets/Animal_malaysia.xlsx
    - assets/Animal_Unique.xlsx
    - assets/Test.jpg

    - assets/Logodict/2.png

    - assets/Logodict/3.png

    - assets/images/promo_banner.jpg
    - assets/images/photo_banner.jpg
    - assets/images/research_banner.jpg
    - assets/images/horticulture_banner.jpeg
    - assets/images/req_banner.jpeg
    - assets/images/poster.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png

    - assets/Logodict/1.PNG

    - assets/Adopt.csv

    - assets/loading/loading.gif

    - assets/arrowleft.png
    - assets/arrowright.png
    - assets/Duit/1.jpg
    - assets/Duit/5.jpg
    - assets/Duit/10.jpg
    - assets/Duit/20.jpg
    - assets/Duit/50.jpg
    - assets/Duit/100.jpg
    - assets/Duit/1000.jpg

    - assets/Bank/maybank.png
    - assets/Bank/ambank.jpg
    - assets/Bank/bsn.png
    - assets/Bank/cimb.jpg
    - assets/Bank/public.jpg
    - assets/Bank/rhb.jpg
    - assets/Bank/sample.jpg
   

    - assets/Donationslide/thankyou.jpg
    - assets/Donationslide/changetoday.png
    - assets/Donationslide/donatedifference.png
    - assets/Bank/FPX.png

    - assets/Zoo/Negara/1.jpg
    - assets/Zoo/Negara/2.jpg
    - assets/Zoo/Negara/3.jpg
    - assets/Zoo/Negara/4.jpg
    - assets/Zoo/Taiping/1.jpg
    - assets/Zoo/Taiping/2.jpeg
    - assets/Zoo/Taiping/3.jpg
    - assets/Zoo/Melaka/1.jpg
    - assets/Zoo/Melaka/2.jpg
    - assets/Zoo/Melaka/3.jpg

    - assets/images/3.jpg
    - assets/images/good.png
    - assets/images/success.png
    - assets/images/bad.png
    - assets/easy.json
    - assets/medium.json
    - assets/hard.json
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/4.jpg
    
    - lib/Setting/lang/en.json
    - lib/Setting/lang/ms.json

    - assets/discover/cover.jpg
    - assets/discover/gajah.jpg
    - assets/discover/images.jpg
    - assets/discover/johor.jpg
    - assets/discover/melaka.jpg
    - assets/discover/taiping.jpg
    - assets/discover/tiger-main.jpg
    - assets/discover/zirrafe.jpg
    - assets/discover/zoo-logo.jpg



    #- assets/AnimalsPicture
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Quando
     fonts:
       -  asset: assets/fonts/quando.regular.ttf
       
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
   - family: Satisfy
     fonts:
       - asset: assets/fonts/Satisfy-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages